# Generated by Django 3.1.4 on 2020-12-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='account_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Regular')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
