# Generated by Django 3.1.4 on 2021-01-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_worker_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'worker', 'verbose_name_plural': 'workers'},
        ),
        migrations.AddField(
            model_name='worker',
            name='is_hub_manager',
            field=models.BooleanField(default=False),
        ),
    ]
