# Generated by Django 3.1.4 on 2020-12-31 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_worker_account_type'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('1', 'Envelope'), ('2', 'Parcel'), ('2', 'Soft'), ('2', 'Freezed')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.supplier'),
        ),
    ]
