# Generated by Django 3.1.4 on 2021-01-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20201231_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('1', 'WITH SUPLIER'), ('2', 'AT GREEN MILE HUB'), ('3', 'REBUNDLING'), ('4', 'ON FLEET'), ('5', 'DELIVERED')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='location',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='packages.shippinglocation'),
        ),
    ]
